# Thông tin định danh dự án trên SonarQube
sonar.projectKey=hoangnguyenkim_KindWave
sonar.projectName=KindWave
sonar.organization=hoangnguyenkim
sonar.projectVersion=1.0

# Server cấu hình cho SonarCloud
sonar.host.url=https://sonarcloud.io

# Đường dẫn tới thư mục chứa mã nguồn (loại trừ thư mục test)
sonar.sources=src, server
# Bỏ qua các file không cần thiết hoặc file sinh tự động
sonar.exclusions=**/node_modules/**, **/dist/**, **/coverage/**, **/*.test.ts, **/*.spec.ts, vite.config.ts

# Đường dẫn tới thư mục chứa code test
sonar.tests=src, server
sonar.test.inclusions=**/*.test.ts, **/*.test.tsx, **/*.spec.ts, **/*.spec.tsx

# Cấu hình đọc báo cáo Coverage (Vì bạn dùng Vitest)
sonar.javascript.lcov.reportPaths=coverage/lcov.info

# Các thông số khác
sonar.sourceEncoding=UTF-8
